Improved backuping
salt-formulas/salt-formula-postgresql pull request #2
Opened 2017-02-13 18:19 UTC by atengler

Improved automated backuping of PostgreSQL databases

2017-02-13 18:52 UTC, fpytloun requested changes
Totally wrong, hard-coded stuff, abusing home directory for temp files, etc.

2017-02-13 20:15 UTC, michaelkuty commented
Probably you mean restoring :D

2017-05-02 12:53 UTC, epcim requested changes
as of now do not provide level required

2017-05-02 12:53 UTC, epcim commented on postgresql/files/restore.sh
> +{%- else %}
else is not appropriate, use `if database.initial_data.engine == "s3"`

2017-05-02 12:53 UTC, epcim commented on postgresql/files/restore.sh
>  {%- set target = "/root/postgresql/data/" %}
avoid to use /root as temporary folder, use /tmp

2017-05-02 12:53 UTC, epcim commented on postgresql/files/restore.sh
>  pg_restore /root/postgresql/data/{{ db_name }}.pg_dump --dbname={{ db_name }} --host=localhost --username={{ database.users[0].name }} --no-password -c
Fix hardcoded path. Use temp directory for this + cleanup.

2017-05-02 12:53 UTC, epcim commented on postgresql/files/restore.sh
>  touch /root/postgresql/flags/{{ db_name }}-installed
This is pretty poor way.
- better to use "postgresql" user directory.
- better to include timestamp

Before file is created, validate db with:
https://serverfault.com/questions/175865/how-to-check-postgresql-database-integrity

2017-05-02 12:53 UTC, epcim commented on postgresql/files/restore.sh
> +gunzip -d -1 -f {{ target }}{{ dest_name }}/var/backups/postgresql/{{ source_name }}
exit if this gunzip fails

2017-05-02 12:53 UTC, epcim commented on postgresql/files/restore.sh
> +pg_restore /root/postgresql/data/{{ dest_name }}/var/backups/postgresql/{{ db_name }}.pg_dump --dbname={{ db_name }} --host=localhost --username={{ database.users[0].name }} --no-password -c
allow restore to alternative db name?

2017-05-02 12:53 UTC, epcim commented on postgresql/files/restore.sh
> +pg_restore /root/postgresql/data/{{ dest_name }}/var/backups/postgresql/{{ db_name }}.pg_dump --dbname={{ db_name }} --host=localhost --username={{ database.users[0].name }} --no-password -c
hardcoded path

2017-05-02 12:53 UTC, epcim commented on postgresql/files/restore.sh
> +duplicity --s3-unencrypted-connection --s3-use-new-style --s3-european-buckets s3+http://{{ database.initial_data.source }}/{{ host }} {{ target }}{{ dest_name }}
make s3+http part of the initial_data.source as it may be "s3+https"

2017-05-02 12:53 UTC, epcim commented on postgresql/files/restore.sh
> +scp backupninja@{{ database.initial_data.source }}:/srv/backupninja/{{ host }}/var/backups/postgresql/postgresql.{{ age }}/{{ source_name }} {{ target }}{{ dest_name }}
hardcoded path

2017-05-02 12:53 UTC, epcim commented on postgresql/files/restore.sh
> +export AWS_ACCESS_KEY_ID={{ database.initial_data.auth.awsaccesskeyid }}
make s3 on aws conditional

2017-05-02 12:57 UTC, fpytloun commented
We shouldn't keep crappy pull requests opened to avoid @epcim reviewing them in a free time :-)
This script needs to be written from scratch, no need to kick into already dead horse.

2017-05-02 12:57 UTC, closed without merging