Change default template
salt-formulas/salt-formula-postgresql pull request #5
Opened 2017-04-22 16:25 UTC by corest

`template1` is used by default for new databases. This allows to setup some default options (extensions for example) for future use by other databases.

2017-04-22 16:25 UTC, cloudlab-autobuild commented
Can one of the admins verify this patch?

2017-04-23 09:33 UTC, fpytloun commented on postgresql/_database.sls
> +    - template: template1
I think it should be configurable like `{{ database.get('template', "template0") }}` or don't use template parameter when not set:
```
{%- if database.template is defined %}
- template: {{ database.template }}
{%- endif %}
```

2017-04-23 09:33 UTC, fpytloun requested changes
See comment above

2017-04-23 09:38 UTC, fpytloun commented on postgresql/_database.sls
> +    - template: template1
FYI @atengler as this will change default behavior (to use what's postgres default which is template1) instead of hard-coded template0.

2017-04-26 08:07 UTC, fpytloun approved these changes

2017-04-26 08:08 UTC, merged